# Generated by Django 4.0.6 on 2022-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_row', models.IntegerField()),
                ('id_of_items', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_time', models.CharField(max_length=20)),
                ('price_rub', models.FloatField()),
            ],
        ),
    ]
